### ISSUE TITLE
How to troubleshoot Resource Based Policies Scan Failures?

### ISSUE THREAD

**Issue by iankowsk** [aws-solutions/account-assessment-for-aws-organizations#31]
After running the Resource-Based Policies scan for all regions and services, the job has been failed with the status "Failed".

How to troubleshoot this error?

**Comment by morjoan** [comment]
Hi, please see our guide for troubleshooting that issue here: 
https://docs.aws.amazon.com/solutions/latest/account-assessment-for-aws-organizations/troubleshooting.html

**Comment by iankowsk** [comment]
After troubleshooting, we have found the following error: 

<img width="1073" alt="Screenshot 2024-09-16 at 10 43 14" src="https://github.com/user-attachments/assets/fe9fa9ea-38b3-4c42-8ecb-6fdc1a5c9c9d">

After adding the following trust policy, the job started with no errors, but it still running for more than 48 hours. 

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

We are unable to take any action.

<img width="1483" alt="Screenshot 2024-09-16 at 10 47 42" src="https://github.com/user-attachments/assets/2b47c420-668b-4cbf-a2db-3dc5a21b2832">

Not able to delete it.

<img width="1483" alt="Screenshot 2024-09-16 at 10 54 27" src="https://github.com/user-attachments/assets/e41ab446-e6f7-4223-85dd-56d4546d3247">

Not able to restart it.

<img width="1486" alt="Screenshot 2024-09-16 at 10 48 44" src="https://github.com/user-attachments/assets/0636ceec-4800-4f99-8b49-d1992a294b54">

There is no lambda function or step functions running. 

<img width="1456" alt="Screenshot 2024-09-16 at 10 50 34" src="https://github.com/user-attachments/assets/fede22fd-335b-441d-a2b1-d849c364a293">


**Questions:** 
1) How can we stop/cancel the current job? 
2) How can we fix the error "The principal states.amazonaws.com it not authorized to assume the provided role"?

**Comment by tbelmega** [comment]
Hi @iankowsk ,
which version of the solution are you running?

The "Scan running" message you see on the UI is related to the "JobStatus" field on the "lastJobMarker" item in DynamoDB table JobHistory. The "FailJob" step you see on the step function diagram is basically the "catch" clause of the step function, supposed to update the JobTable and and set the "lastJobMarker" from "RUNNING" to "FAILED". Since this update failed, the solution treats the job as still running and can't start another one.
This is obviously not supposed to happen. The immediate solution is to manually update the JobStatus field in DynamoDB from "RUNNING" to "FAILED" (see screenshot).

![image](https://github.com/user-attachments/assets/40c7df17-ce45-423a-80f9-f4483d71d85d)

To be clear, no compute is technically "running", so the customer isn't billed for anything. It's just that the database entry representing the Job hasn't been updated from "RUNNING" to "FAILED" as it should have, so the solution logic treats the state as if a job was running and doesn't let you start a new one.

Regarding the actual cause for the failure, I can't tell why it fails to assume the role. Please contact me directly internally, I can help troubleshoot on Thursday or Friday if that helps.

**Comment by iankowsk** [comment]
Thanks for the quick reply, @tbelmega. 

I will reach out to you to discuss how we can solve the role issue.

**Comment by tbelmega** [comment]
Scheduled a troubleshooting session internally, closing this ticket.
